import type { EnemyDef } from '../types'

export const ENEMIES: EnemyDef[] = [
  {
    id: 'shardling',
    name: '샤드링',
    title: '부서진 잔광',
    difficulty: 'NORMAL',
    hp: 420,
    atk: 48,
    def: 18,
    aiDepth: 1,
    skills: [{ id: 'nibble', name: '파편 할퀴기', weight: 1, power: 1, kind: 'damage' }],
  },
  {
    id: 'echo-wisp',
    name: '에코 위습',
    title: '기억의 연기',
    difficulty: 'NORMAL',
    hp: 480,
    atk: 52,
    def: 22,
    aiDepth: 1,
    skills: [
      { id: 'sip', name: '메아리 흡수', weight: 1, power: 0.85, kind: 'drain' },
      { id: 'sting', name: '잔향 찌르기', weight: 1, power: 1.05, kind: 'damage' },
    ],
  },
  {
    id: 'rust-sentinel',
    name: '러스트 센티널',
    title: '녹슨 수호체',
    difficulty: 'NORMAL',
    hp: 560,
    atk: 55,
    def: 36,
    aiDepth: 1,
    passive: 'GUARD 매치에 약함',
    skills: [{ id: 'bash', name: '강타', weight: 1, power: 1.1, kind: 'damage' }],
  },
  {
    id: 'volt-mite',
    name: '볼트 마이트',
    title: '전하 기생체',
    difficulty: 'NORMAL',
    hp: 500,
    atk: 62,
    def: 20,
    aiDepth: 1,
    skills: [{ id: 'zap', name: '스파크', weight: 1, power: 1.15, kind: 'damage' }],
  },
  {
    id: 'mire-lurker',
    name: '마이어 러커',
    title: '늪의 잠복자',
    difficulty: 'HARD',
    hp: 640,
    atk: 68,
    def: 40,
    aiDepth: 2,
    skills: [
      { id: 'soak', name: '진흙 속박', weight: 1, power: 0.9, kind: 'damage' },
      { id: 'regen', name: '습지 재생', weight: 0.7, power: 0.6, kind: 'heal' },
    ],
  },
  {
    id: 'glass-archer',
    name: '글래스 아처',
    title: '수정 저격수',
    difficulty: 'HARD',
    hp: 580,
    atk: 78,
    def: 24,
    aiDepth: 2,
    skills: [{ id: 'pierce', name: '관통 사격', weight: 1, power: 1.25, kind: 'pierce' }],
  },
  {
    id: 'cinder-brute',
    name: '신더 브루트',
    title: '잿불 거인',
    difficulty: 'HARD',
    hp: 760,
    atk: 72,
    def: 48,
    aiDepth: 2,
    skills: [{ id: 'slam', name: '잿불 강타', weight: 1, power: 1.2, kind: 'damage' }],
  },
  {
    id: 'null-priest',
    name: '널 프리스트',
    title: '공허 사제',
    difficulty: 'HARD',
    hp: 700,
    atk: 70,
    def: 38,
    aiDepth: 2,
    skills: [
      { id: 'hex', name: '공허 저주', weight: 1, power: 1.1, kind: 'damage' },
      { id: 'drain', name: '의지 갈취', weight: 0.8, power: 1, kind: 'drain' },
    ],
  },
  {
    id: 'helix-drone',
    name: '헬릭스 드론',
    title: '나선 정찰기',
    difficulty: 'HARD',
    hp: 720,
    atk: 74,
    def: 42,
    aiDepth: 2,
    skills: [{ id: 'beam', name: '나선 빔', weight: 1, power: 1.15, kind: 'damage' }],
  },
  {
    id: 'elite-warden',
    name: '엘리트 워든',
    title: '관문 수호자',
    difficulty: 'ELITE',
    hp: 980,
    atk: 88,
    def: 60,
    aiDepth: 2,
    boardMechanic: 'lock',
    skills: [
      { id: 'lockdown', name: '봉쇄', weight: 0.8, power: 0.9, kind: 'lock' },
      { id: 'cleave', name: '참격', weight: 1, power: 1.3, kind: 'damage' },
    ],
  },
  {
    id: 'elite-siren',
    name: '엘리트 사이렌',
    title: '공명 유혹자',
    difficulty: 'ELITE',
    hp: 920,
    atk: 96,
    def: 44,
    aiDepth: 3,
    skills: [
      { id: 'charm', name: '유혹의 파동', weight: 1, power: 1.2, kind: 'drain' },
      { id: 'song', name: '파열음', weight: 1, power: 1.35, kind: 'damage' },
    ],
  },
  {
    id: 'elite-forge',
    name: '엘리트 포지',
    title: '용광 기갑',
    difficulty: 'ELITE',
    hp: 1100,
    atk: 92,
    def: 70,
    aiDepth: 3,
    boardMechanic: 'corrupt',
    skills: [
      { id: 'corrupt', name: '오염 주입', weight: 0.9, power: 1, kind: 'corrupt' },
      { id: 'erupt', name: '용암 분출', weight: 1, power: 1.4, kind: 'damage' },
    ],
  },
  {
    id: 'boss-aetherion',
    name: '에테르리온',
    title: '제1장 · 심핵 감시자',
    difficulty: 'BOSS',
    hp: 1480,
    atk: 98,
    def: 68,
    aiDepth: 3,
    boardMechanic: 'corrupt',
    passive: '페이즈마다 보드 오염 · 강공격',
    phases: [
      { hpRatio: 1, label: '관측', atkMul: 1, note: '패턴 학습' },
      { hpRatio: 0.6, label: '각성', atkMul: 1.25, note: '오염 주기 단축' },
      { hpRatio: 0.3, label: '붕괴', atkMul: 1.45, note: '강공격 강화' },
    ],
    skills: [
      { id: 'gaze', name: '심핵의 시선', weight: 1, power: 1.2, kind: 'damage' },
      { id: 'pollute', name: '코어 오염', weight: 0.9, power: 1, kind: 'corrupt' },
      { id: 'judgment', name: '심판 파동', weight: 0.7, power: 1.6, kind: 'damage' },
    ],
  },
]

export function enemyById(id: string): EnemyDef | undefined {
  return ENEMIES.find((e) => e.id === id)
}
