import type { AssetSpec } from './types'

export const GARAGE_ASSETS: AssetSpec[] = [
  {
    id: 'ASSET_GARAGE_BACKGROUND',
    kind: 'environment',
    labelKo: '자동차 공방 배경',
    usage: '자동차 공방 전체 스테이지 배경 (선택·조립·색칠·운전 공통 화풍)',
    size: { w: 2048, h: 1536 },
    transparentBackground: false,
    states: ['day'],
    animationRequirements: '정적 또는 미세 ambient(먼지/빛). 배경 속 자동차·캐릭터 crop 재사용 금지.',
    status: 'ASSET_REQUIRED',
    baselineGroup: 'garage',
    qualityGateNotes:
      '공방·세차장·정비소·도로·마을과 동일 perspective/lighting/saturation/shape/material/outline 정책.',
  },
  {
    id: 'ASSET_GARAGE_WORKBENCH',
    kind: 'prop',
    labelKo: '공방 작업대',
    usage: '조립·색칠 스테이지 소품',
    size: { w: 1024, h: 768 },
    transparentBackground: true,
    status: 'ASSET_REQUIRED',
    baselineGroup: 'garage',
  },
  {
    id: 'ASSET_GARAGE_TOOL_RACK',
    kind: 'prop',
    labelKo: '공구 랙',
    usage: '공방 밀도/분위기 소품',
    size: { w: 768, h: 1024 },
    transparentBackground: true,
    status: 'ASSET_REQUIRED',
    baselineGroup: 'garage',
  },
]

export const OTHER_VEHICLE_PLACEHOLDERS: AssetSpec[] = [
  {
    id: 'ASSET_EXCAVATOR_SET',
    kind: 'vehicle_part',
    labelKo: '굴착기 세트',
    usage: '확장 차량 — FIRE_TRUCK_01 기준 승인 후',
    size: { w: 1024, h: 768 },
    transparentBackground: true,
    partStructure: ['body', 'cabin', 'trackLeft', 'trackRight', 'boom', 'arm', 'bucket', 'window', 'shadow'],
    status: 'ASSET_REQUIRED',
    qualityGateNotes: '기준 트라이어드 승인 전 제작 금지.',
  },
  {
    id: 'ASSET_DUMPTRUCK_SET',
    kind: 'vehicle_part',
    labelKo: '덤프트럭 세트',
    usage: '확장 차량 — 기준 승인 후',
    size: { w: 1024, h: 768 },
    transparentBackground: true,
    status: 'ASSET_REQUIRED',
  },
  {
    id: 'ASSET_AMBULANCE_SET',
    kind: 'vehicle_part',
    labelKo: '구급차 세트',
    usage: '확장 차량 — 기준 승인 후',
    size: { w: 1024, h: 768 },
    transparentBackground: true,
    status: 'ASSET_REQUIRED',
  },
  {
    id: 'ASSET_POLICE_SET',
    kind: 'vehicle_part',
    labelKo: '경찰차 세트',
    usage: '확장 차량 — 기준 승인 후',
    size: { w: 1024, h: 768 },
    transparentBackground: true,
    status: 'ASSET_REQUIRED',
  },
  {
    id: 'ASSET_CRANE_SET',
    kind: 'vehicle_part',
    labelKo: '크레인 세트',
    usage: '확장 차량 — 기준 승인 후',
    size: { w: 1024, h: 768 },
    transparentBackground: true,
    status: 'ASSET_REQUIRED',
  },
]
