export type {
  RecordFacing,
  RecordMode,
  RecordPhase,
  RecordedClip,
  ScreenRecordState,
} from './types'
export {
  cancelRecording,
  clearElapsedTicker,
  autoSaveClipToAlbum,
  extForMime,
  formatBytes,
  formatElapsed,
  getElapsedMs,
  isLikelyIos,
  isRecordingActive,
  pickRecorderMime,
  revokeUrl,
  shareOrDownloadClip,
  startElapsedTicker,
  startRecording,
  stopRecording,
  supportsDisplayCapture,
  supportsMediaRecorder,
  supportsUserMedia,
} from './recorder'
export {
  bindScreenRecordScreen,
  defaultScreenRecordState,
  getLastClip,
  removeFloatDock,
  renderScreenRecordScreen,
  teardownScreenRecord,
} from './ui/recordScreen'
