import type { AizioSkill, CoreIntent } from './types'

/** Metadata registry — skill modules load on demand. */
const SKILLS: AizioSkill[] = [
  {
    id: 'music',
    displayName: 'AIZIO Music',
    supportedIntents: ['play_music', 'control_music'],
    available: true,
    timeoutMs: 12_000,
    safetyLevel: 1,
    load: () => import('./skills/musicSkillAdapter'),
  },
  {
    id: 'translation',
    displayName: 'AIZIO Translation',
    supportedIntents: ['translate'],
    available: true,
    timeoutMs: 20_000,
    safetyLevel: 1,
    load: () => import('./skills/translationSkillAdapter'),
  },
  {
    id: 'note',
    displayName: 'AIZIO Notes',
    supportedIntents: ['create_note', 'search_note'],
    available: true,
    timeoutMs: 5_000,
    safetyLevel: 2,
    load: () => import('./skills/noteSkillAdapter'),
  },
  {
    id: 'todo',
    displayName: 'AIZIO Todos',
    supportedIntents: ['create_todo', 'update_todo', 'list_todo'],
    available: true,
    timeoutMs: 5_000,
    safetyLevel: 2,
    load: () => import('./skills/todoSkillAdapter'),
  },
  {
    id: 'calendar',
    displayName: 'AIZIO Calendar',
    supportedIntents: ['create_calendar_event', 'list_calendar'],
    available: true, // list partial; create reports unavailable inside skill
    timeoutMs: 5_000,
    safetyLevel: 2,
    load: () => import('./skills/calendarSkillAdapter'),
  },
  {
    id: 'relationship',
    displayName: 'AIZIO Relationship Memory',
    supportedIntents: [
      'remember_relationship',
      'update_relationship',
      'forget_relationship',
      'list_relationships',
    ],
    available: true,
    timeoutMs: 5_000,
    safetyLevel: 2,
    load: () => import('./skills/relationshipSkillAdapter'),
  },
  {
    id: 'smartReminder',
    displayName: 'AIZIO Smart Reminder',
    supportedIntents: [
      'create_reminder',
      'update_reminder',
      'cancel_reminder',
      'list_reminders',
      'snooze_reminder',
      'mark_reminder_complete',
      'ask_person_schedule',
    ],
    available: true,
    timeoutMs: 8_000,
    safetyLevel: 2,
    load: () => import('./skills/smartReminderSkillAdapter'),
  },
  {
    id: 'lifeOS2',
    displayName: 'AIZIO Life OS 2.0',
    supportedIntents: [
      'ask_current_context',
      'ask_priority',
      'ask_prediction',
      'show_habits',
      'confirm_habit',
      'reject_habit',
      'start_focus',
      'stop_focus',
      'focus_status',
      'save_relationship_ext',
      'search_relationship_ext',
      'search_knowledge',
      'create_automation',
      'run_automation',
      'stop_automation',
      'goal_coaching',
      'morning_brief',
      'evening_summary',
      'show_recommendations',
    ],
    available: true,
    timeoutMs: 20_000,
    safetyLevel: 2,
    load: () => import('./skills/lifeOS2SkillAdapter'),
  },
  {
    id: 'lifeOS',
    displayName: 'AIZIO Life OS',
    supportedIntents: [
      'remember_preference',
      'update_preference',
      'forget_preference',
      'show_dna',
      'create_goal',
      'update_goal',
      'list_goals',
      'complete_goal',
      'create_project_item',
      'project_status',
      'project_planning',
      'save_idea',
      'search_ideas',
      'run_ai_meeting',
      'create_routine',
      'run_routine',
      'show_timeline',
      'add_timeline_event',
      'family_overview',
      'emergency_help',
      'health_log',
      'finance_log',
      'create_travel_plan',
      'create_learning_plan',
      'list_skills',
      'enable_skill',
      'disable_skill',
      'life_today_brief',
    ],
    available: true,
    timeoutMs: 25_000,
    safetyLevel: 2,
    load: () => import('./skills/lifeOSSkillAdapter'),
  },
  {
    id: 'project',
    displayName: 'AIZIO Projects (legacy stub)',
    supportedIntents: [],
    available: false,
    timeoutMs: 3_000,
    safetyLevel: 1,
    load: () => import('./skills/projectSkillAdapter'),
  },
  {
    id: 'settings',
    displayName: 'AIZIO Settings',
    supportedIntents: ['change_setting'],
    available: true,
    timeoutMs: 3_000,
    safetyLevel: 2,
    load: () => import('./skills/settingsSkillAdapter'),
  },
  {
    id: 'navigation',
    displayName: 'AIZIO Navigation',
    supportedIntents: ['app_navigation'],
    available: true,
    timeoutMs: 3_000,
    safetyLevel: 1,
    load: () => import('./skills/navigationSkillAdapter'),
  },
  {
    id: 'help',
    displayName: 'AIZIO Help',
    supportedIntents: ['help'],
    available: true,
    timeoutMs: 3_000,
    safetyLevel: 1,
    load: () => import('./skills/helpSkillAdapter'),
  },
  {
    id: 'chat',
    displayName: 'AIZIO Chat',
    supportedIntents: ['general_chat', 'ask_information', 'summarize', 'unknown'],
    available: true,
    timeoutMs: 45_000,
    safetyLevel: 1,
    load: () => import('./skills/chatSkillAdapter'),
  },
]

export function listSkillMeta(): Array<{
  id: string
  displayName: string
  supportedIntents: CoreIntent[]
  available: boolean
}> {
  return SKILLS.map((s) => ({
    id: s.id,
    displayName: s.displayName,
    supportedIntents: s.supportedIntents,
    available: s.available,
  }))
}

export function findSkillsForIntent(intent: CoreIntent): AizioSkill[] {
  return SKILLS.filter((s) => s.supportedIntents.includes(intent))
}

export function getSkillById(id: string): AizioSkill | undefined {
  return SKILLS.find((s) => s.id === id)
}
